language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
before_script:
  - mkdir output
script:
  - python sentiment_tester.py
after_script:
  - cd output
  - if [[ -s sentiment.txt ]]; then echo "# File sentiment.txt found"; else echo "File sentiment.txt not found"; exit 1; fi
  - if [[ -s sentiment.csv ]]; then echo "# File sentiment.csv found"; else echo "File sentiment.csv not found"; exit 1; fi
  - cat sentiment.txt
  - cat sentiment.csv
  - if [[ `wc -l sentiment.csv | cut -d' ' -f1` -gt 1 ]]; then echo "# File sentiment.csv may be valid"; else echo "File sentiment.csv is not valid"; exit 1; fi