language: python
python:
  - "3.8"
branches:
  only:
    - development
install:
  - pip install -r requirements.txt
script:
  - sentiment_tester.py
after_script:
  - cd output
  - cat sentiment.csv
  - cat sentiment.txt'